## Import libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Load datasets (using from seaborn)

In [15]:
data = sns.load_dataset('tips')
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
data.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [17]:
data.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [18]:
data['sex'].value_counts() #only for categorical data

sex
Male      157
Female     87
Name: count, dtype: int64

In [19]:
data['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [20]:
data['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [21]:
data['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [22]:
X=data.drop('total_bill', axis=1)
y=data['total_bill']

In [23]:
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
  X, y,
  test_size=0.25,
)

#train size can also be used in place of test size

In [26]:
X_train

      tip     sex smoker   day    time  size
51   2.60  Female     No   Sun  Dinner     2
81   3.40    Male     No  Thur   Lunch     2
140  3.50  Female     No  Thur   Lunch     2
130  1.50    Male     No  Thur   Lunch     2
138  2.00    Male    Yes  Thur   Lunch     2
..    ...     ...    ...   ...     ...   ...
192  2.56    Male    Yes  Thur   Lunch     2
241  2.00    Male    Yes   Sat  Dinner     2
34   3.27    Male     No   Sat  Dinner     2
113  2.55    Male     No   Sun  Dinner     2
133  2.00  Female     No  Thur   Lunch     2

[183 rows x 6 columns]

In [27]:
y_train

51     10.29
81     16.66
140    17.47
130    19.08
138    16.00
       ...
192    28.44
241    22.67
34     17.78
113    23.95
133    12.26
Name: total_bill, Length: 183, dtype: float64

In [30]:
day=pd.get_dummies(X_train['day'])
day

      Thur    Fri    Sat    Sun
161  False  False  False   True
50   False  False  False   True
22   False  False   True  False
101  False   True  False  False
221  False   True  False  False
..     ...    ...    ...    ...
227  False  False   True  False
106  False  False   True  False
64   False  False   True  False
157  False  False  False   True
111  False  False   True  False

[183 rows x 4 columns]

In [31]:
X_train.drop('day',axis=1,inplace=True)
X_train=pd.concat([X_train,day],axis=1)

In [32]:
X_train

      tip     sex smoker    time  size   Thur    Fri    Sat    Sun
161  2.50    Male     No  Dinner     2  False  False  False   True
50   2.50    Male     No  Dinner     2  False  False  False   True
22   2.23  Female     No  Dinner     2  False  False   True  False
101  3.00  Female    Yes  Dinner     2  False   True  False  False
221  3.48  Female    Yes   Lunch     2  False   True  False  False
..    ...     ...    ...     ...   ...    ...    ...    ...    ...
227  3.00    Male     No  Dinner     4  False  False   True  False
106  4.06    Male    Yes  Dinner     2  False  False   True  False
64   2.64    Male     No  Dinner     3  False  False   True  False
157  3.75  Female     No  Dinner     4  False  False  False   True
111  1.00  Female     No  Dinner     1  False  False   True  False

[183 rows x 9 columns]

In [ ]:
sex=pd.get_dummies(X_train['sex'])
X_train.drop('day',axis=1,inplace=True)
X_train=pd.concat([X_train,day],axis=1)

In [ ]:
time=pd.get_dummies(X_train['time'])
X_train.drop('day',axis=1,inplace=True)
X_train=pd.concat([X_train,day],axis=1)

In [ ]:
smoker=pd.get_dummies(X_train['smoker'])
X_train.drop('day',axis=1,inplace=True)
X_train=pd.concat([X_train,day],axis=1)

In [ ]:
from sklearn.svm import SVR
model=SVR()
model.fit(X_train,y_train)